/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 untitled.glb 
*/

import React, { useRef, forwardRef } from "react"
import { useGLTF, useAnimations } from "@react-three/drei"

const Model = forwardRef((props, ref) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF("untitled.glb")
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={ref} {...props} dispose={null}>
      <group name="Scene">
        <group name="icecream" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="Root">
            <primitive object={nodes.Hips} />
            <group name="Newton_Headless">
              <skinnedMesh
                name="Newton_Headless_Mesh"
                geometry={nodes.Newton_Headless_Mesh.geometry}
                material={materials.Head1}
                skeleton={nodes.Newton_Headless_Mesh.skeleton}
              />
              <skinnedMesh
                name="Newton_Headless_Mesh_1"
                geometry={nodes.Newton_Headless_Mesh_1.geometry}
                material={materials.RKK_Joint}
                skeleton={nodes.Newton_Headless_Mesh_1.skeleton}
              />
            </group>
            <group name="Newton_HeadFace">
              <skinnedMesh
                name="Newton_HeadFace_Mesh"
                geometry={nodes.Newton_HeadFace_Mesh.geometry}
                material={materials["Material #22"]}
                skeleton={nodes.Newton_HeadFace_Mesh.skeleton}
                morphTargetDictionary={
                  nodes.Newton_HeadFace_Mesh.morphTargetDictionary
                }
                morphTargetInfluences={
                  nodes.Newton_HeadFace_Mesh.morphTargetInfluences
                }
              />
              <skinnedMesh
                name="Newton_HeadFace_Mesh_1"
                geometry={nodes.Newton_HeadFace_Mesh_1.geometry}
                material={materials["Head1.001"]}
                skeleton={nodes.Newton_HeadFace_Mesh_1.skeleton}
                morphTargetDictionary={
                  nodes.Newton_HeadFace_Mesh_1.morphTargetDictionary
                }
                morphTargetInfluences={
                  nodes.Newton_HeadFace_Mesh_1.morphTargetInfluences
                }
              />
              <skinnedMesh
                name="Newton_HeadFace_Mesh_2"
                geometry={nodes.Newton_HeadFace_Mesh_2.geometry}
                material={materials["Material #21"]}
                skeleton={nodes.Newton_HeadFace_Mesh_2.skeleton}
                morphTargetDictionary={
                  nodes.Newton_HeadFace_Mesh_2.morphTargetDictionary
                }
                morphTargetInfluences={
                  nodes.Newton_HeadFace_Mesh_2.morphTargetInfluences
                }
              />
              <skinnedMesh
                name="Newton_HeadFace_Mesh_3"
                geometry={nodes.Newton_HeadFace_Mesh_3.geometry}
                material={materials.Pupil}
                skeleton={nodes.Newton_HeadFace_Mesh_3.skeleton}
                morphTargetDictionary={
                  nodes.Newton_HeadFace_Mesh_3.morphTargetDictionary
                }
                morphTargetInfluences={
                  nodes.Newton_HeadFace_Mesh_3.morphTargetInfluences
                }
              />
              <skinnedMesh
                name="Newton_HeadFace_Mesh_4"
                geometry={nodes.Newton_HeadFace_Mesh_4.geometry}
                material={materials.Lens}
                skeleton={nodes.Newton_HeadFace_Mesh_4.skeleton}
                morphTargetDictionary={
                  nodes.Newton_HeadFace_Mesh_4.morphTargetDictionary
                }
                morphTargetInfluences={
                  nodes.Newton_HeadFace_Mesh_4.morphTargetInfluences
                }
              />
              <skinnedMesh
                name="Newton_HeadFace_Mesh_5"
                geometry={nodes.Newton_HeadFace_Mesh_5.geometry}
                material={materials.sclera}
                skeleton={nodes.Newton_HeadFace_Mesh_5.skeleton}
                morphTargetDictionary={
                  nodes.Newton_HeadFace_Mesh_5.morphTargetDictionary
                }
                morphTargetInfluences={
                  nodes.Newton_HeadFace_Mesh_5.morphTargetInfluences
                }
              />
              <skinnedMesh
                name="Newton_HeadFace_Mesh_6"
                geometry={nodes.Newton_HeadFace_Mesh_6.geometry}
                material={materials.Iris}
                skeleton={nodes.Newton_HeadFace_Mesh_6.skeleton}
                morphTargetDictionary={
                  nodes.Newton_HeadFace_Mesh_6.morphTargetDictionary
                }
                morphTargetInfluences={
                  nodes.Newton_HeadFace_Mesh_6.morphTargetInfluences
                }
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
})

Model.displayName = "Model"
useGLTF.preload("/untitled.glb")

export default Model
