/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 test.gltf 
*/

import React, { useRef } from "react"
import { useGLTF, useAnimations } from "@react-three/drei"

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF("/test.gltf")
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="default">
        <group name="icecream">
          <group name="Root">
            <primitive object={nodes.Hips} />
            <skinnedMesh
              name="Newton_HeadFaceless"
              geometry={nodes.Newton_HeadFaceless.geometry}
              material={materials.Default}
              skeleton={nodes.Newton_HeadFaceless.skeleton}
            />
            <skinnedMesh
              name="Newton_Headless"
              geometry={nodes.Newton_Headless.geometry}
              material={materials.Default}
              skeleton={nodes.Newton_Headless.skeleton}
            />
            <skinnedMesh
              name="Newton_HeadFace"
              geometry={nodes.Newton_HeadFace.geometry}
              material={materials.Default}
              skeleton={nodes.Newton_HeadFace.skeleton}
              morphTargetDictionary={
                nodes.Newton_HeadFace.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.Newton_HeadFace.morphTargetInfluences
              }
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload("/test.gltf")
