export function mappedPart(nodeName) {
  const boneMapping = {
    Hips: "hip",
    Spine1: "spine",
    // Spine2: "spine2",
    // Spine3: "spine3",
    // Spine4: "spine4",
    Neck: "neck",
    Head: "head",
    RightShoulder: "rightShoulder",
    RightArm: "rightUpperArm",
    RightForeArm: "rightLowerArm",
    RightHand: "rightHand",
    RightFinger1Metacarpal: "rightThumbMetacarpal",
    RightFinger1Proximal: "rightThumbProximal",
    RightFinger1Distal: "rightThumbDistal",
    RightFinger5Metacarpal: "rightLittleFingerMetacarpal",
    RightFinger5Proximal: "rightLittleFingerProximal",
    RightFinger5Medial: "rightLittleFingerMedial",
    RightFinger5Distal: "rightLittleFingerDistal",
    RightFinger4Metacarpal: "rightRingFingerMetacarpal",
    RightFinger4Proximal: "rightRingFingerProximal",
    RightFinger4Medial: "rightRingFingerMedial",
    RightFinger4Distal: "rightRingFingerDistal",
    RightFinger3Metacarpal: "rightMiddleFingerMetacarpal",
    RightFinger3Proximal: "rightMiddleFingerProximal",
    RightFinger3Medial: "rightMiddleFingerMedial",
    RightFinger3Distal: "rightMiddleFingerDistal",
    RightFinger2Metacarpal: "rightIndexFingerMetacarpal",
    RightFinger2Proximal: "rightIndexFingerProximal",
    RightFinger2Medial: "rightIndexFingerMedial",
    RightFinger2Distal: "rightIndexFingerDistal",
    LeftShoulder: "leftShoulder",
    LeftArm: "leftUpperArm",
    LeftForeArm: "leftLowerArm",
    LeftHand: "leftHand",
    LeftFinger5Metacarpal: "leftLittleFingerMetacarpal",
    LeftFinger5Proximal: "leftLittleFingerProximal",
    LeftFinger5Medial: "leftLittleFingerMedial",
    LeftFinger5Distal: "leftLittleFingerDistal",
    LeftFinger4Metacarpal: "leftRingFingerMetacarpal",
    LeftFinger4Proximal: "leftRingFingerProximal",
    LeftFinger4Medial: "leftRingFingerMedial",
    LeftFinger4Distal: "leftRingFingerDistal",
    LeftFinger3Metacarpal: "leftMiddleFingerMetacarpal",
    LeftFinger3Proximal: "leftMiddleFingerProximal",
    LeftFinger3Medial: "leftMiddleFingerMedial",
    LeftFinger3Distal: "leftMiddleFingerDistal",
    LeftFinger2Metacarpal: "leftIndexFingerMetacarpal",
    LeftFinger2Proximal: "leftIndexFingerProximal",
    LeftFinger2Medial: "leftIndexFingerMedial",
    LeftFinger2Distal: "leftIndexFingerDistal",
    LeftFinger1Metacarpal: "leftThumbMetacarpal",
    LeftFinger1Proximal: "leftThumbProximal",
    LeftFinger1Distal: "leftThumbDistal",
    RightThigh: "rightThigh",
    RightShin: "rightLeg",
    RightFoot: "rightFoot",
    RightToe: "rightToe",
    LeftThigh: "leftThigh",
    LeftShin: "leftLeg",
    LeftFoot: "leftFoot",
    LeftToe: "leftToe",
  }

  return boneMapping[nodeName] || null
}
